<?php
  $labels['ttrss'] = 'TTRSS';
  $labels['rss'] = 'RSS';
  $labels['url'] = 'URL';
  $labels['rss_settings'] = 'Paramètre de TTRSS';
  $labels['add'] = 'Ajouter';
  $labels['remove'] = 'Enlever';
  $labels['add_label'] = 'Ajouter étiquette';
  $labels['remove_label'] = 'Enlever étiquette';
  $labels['feed_subscribe'] = 'Nouvel abonnement';
  $labels['feed_unsubscribe'] = 'Se désabonner';
  $labels['autoread'] = 'Ne pas marquer les articles lus à la lecture;
  $labels['showonlyunread'] = 'Affiche que les éléments non lus';
?>
